apiVersion: v1
kind: Service
metadata:
  name: hotel-service
spec:
  type: ClusterIP
  ports:
    - port: 82
      targetPort: 82
  selector:
    app: hotel-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-app
  template:
    metadata:
      labels:
        app: hotel-app
    spec:
      containers:
        - name: hotel-service-container
          image: krishanx92/hotel:1.0.0
          ports:
            - containerPort: 81
